# Generated by Django 4.1.8 on 2023-05-03 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_contact_no_self_rating_contact_no_self_rating'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='no_self_rating',
        ),
    ]
