# Generated by Django 4.1.8 on 2023-05-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_contact_no_self_rating'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='no_self_rating',
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(check=models.Q(('user_from', models.F('user_to')), _negated=True), name='no_self_follow'),
        ),
    ]
